version: '3.2'

services:
  express-server-dev:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: ./DockerFile
    ports:
      - 23000:23000
    # Environment setting no effect on NAS server
    # environment:
    #   - PARSE_SERVER_URL=https://parse-dev.fungwingstar.com/parse
    #   - PARSE_SERVER_APP_ID=fungwingplus_dev
